pluginManagement {
	repositories {
		mavenLocal()
		mavenCentral()
		gradlePluginPortal()
	}
}

plugins {
	id "se.bjurr.gradle.bundle-jar" version "2.1.1" apply false
	id "se.bjurr.gradle.shadow" version "2.1.1" apply false
}

rootProject.name = "violations-git-lib-base"

include "violations-git-lib-transitives","violations-git-lib"
